# Generated by Django 2.2.7 on 2019-11-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191118_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartDetail',
        ),
    ]
